// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:predix.eventhub.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .predix.eventhub.AckStatus status_code = 2;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .predix.eventhub.AckStatus status_code = 2;</code>
   */
  com.ge.predix.eventhub.stub.AckStatus getStatusCode();

  /**
   * <code>optional string desc = 3;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>optional string topic = 4;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  java.lang.String getTopic();
  /**
   * <code>optional string topic = 4;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>optional int32 partition = 5;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  int getPartition();

  /**
   * <code>optional int64 offset = 6;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  long getOffset();

  /**
   * <code>optional .predix.eventhub.Timestamp timestamp = 7;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  boolean hasTimestamp();
  /**
   * <code>optional .predix.eventhub.Timestamp timestamp = 7;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  com.ge.predix.eventhub.stub.Timestamp getTimestamp();
  /**
   * <code>optional .predix.eventhub.Timestamp timestamp = 7;</code>
   *
   * <pre>
   * this you will only get this the ack is a success
   * </pre>
   */
  com.ge.predix.eventhub.stub.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>optional bytes body = 8;</code>
   *
   * <pre>
   * you will only get this if the ack is a failure .
   * </pre>
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>optional string zone_id = 9;</code>
   *
   * <pre>
   * you will only get this if the ack is a failure .
   * </pre>
   */
  java.lang.String getZoneId();
  /**
   * <code>optional string zone_id = 9;</code>
   *
   * <pre>
   * you will only get this if the ack is a failure .
   * </pre>
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <code>map&lt;string, string&gt; tags = 10;</code>
   *
   * <pre>
   * you will only get this if the ack is a failure .
   * </pre>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTags();

  /**
   * <code>optional bytes key = 11;</code>
   *
   * <pre>
   * you will only get this if the ack is a failure .
   * </pre>
   */
  com.google.protobuf.ByteString getKey();
}
