// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

public final class EventHubService {
  private EventHubService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_Timestamp_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_Timestamp_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_Message_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_Message_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_Message_TagsEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_Message_TagsEntry_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_Ack_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_Ack_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_Ack_TagsEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_Ack_TagsEntry_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_Messages_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_Messages_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_PublishRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_PublishRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_SubscriptionMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_SubscriptionMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_PublishResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_PublishResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_SubscriptionResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_SubscriptionResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_SubscriptionAcks_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_SubscriptionAcks_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_predix_eventhub_SubscriptionRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_predix_eventhub_SubscriptionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016EventHub.proto\022\017predix.eventhub\"+\n\tTim" +
      "estamp\022\017\n\007seconds\030\001 \001(\003\022\r\n\005nanos\030\002 \001(\005\"\201" +
      "\002\n\007Message\022\n\n\002id\030\001 \001(\t\022\014\n\004body\030\002 \001(\014\022\017\n\007" +
      "zone_id\030\003 \001(\t\0220\n\004tags\030\004 \003(\0132\".predix.eve" +
      "nthub.Message.TagsEntry\022\013\n\003key\030\005 \001(\014\022\r\n\005" +
      "topic\030\006 \001(\t\022\021\n\tpartition\030\007 \001(\005\022\016\n\006offset" +
      "\030\010 \001(\003\022-\n\ttimestamp\030\t \001(\0132\032.predix.event" +
      "hub.Timestamp\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"\270\002\n\003Ack\022\n\n\002id\030\001 \001(\t\022/" +
      "\n\013status_code\030\002 \001(\0162\032.predix.eventhub.Ac",
      "kStatus\022\014\n\004desc\030\003 \001(\t\022\r\n\005topic\030\004 \001(\t\022\021\n\t" +
      "partition\030\005 \001(\005\022\016\n\006offset\030\006 \001(\003\022-\n\ttimes" +
      "tamp\030\007 \001(\0132\032.predix.eventhub.Timestamp\022\014" +
      "\n\004body\030\010 \001(\014\022\017\n\007zone_id\030\t \001(\t\022,\n\004tags\030\n " +
      "\003(\0132\036.predix.eventhub.Ack.TagsEntry\022\013\n\003k" +
      "ey\030\013 \001(\014\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"1\n\010Messages\022%\n\003msg\030\001 \003(\0132\030" +
      ".predix.eventhub.Message\"=\n\016PublishReque" +
      "st\022+\n\010messages\030\001 \001(\0132\031.predix.eventhub.M" +
      "essages\"B\n\023SubscriptionMessage\022+\n\010messag",
      "es\030\001 \001(\0132\031.predix.eventhub.Messages\"4\n\017P" +
      "ublishResponse\022!\n\003ack\030\001 \003(\0132\024.predix.eve" +
      "nthub.Ack\"9\n\024SubscriptionResponse\022!\n\003ack" +
      "\030\001 \003(\0132\024.predix.eventhub.Ack\"5\n\020Subscrip" +
      "tionAcks\022!\n\003ack\030\001 \003(\0132\024.predix.eventhub." +
      "Ack\"O\n\023SubscriptionRequest\022\017\n\007zone_id\030\001 " +
      "\001(\t\022\022\n\nsubscriber\030\002 \001(\t\022\023\n\013instance_id\030\003" +
      " \001(\t*M\n\tAckStatus\022\014\n\010ACCEPTED\020\000\022\017\n\013BAD_R" +
      "EQUEST\020\001\022\025\n\021REQUEST_TOO_LARGE\020\002\022\n\n\006FAILE" +
      "D\020\0032\\\n\tPublisher\022O\n\004send\022\037.predix.eventh",
      "ub.PublishRequest\032 .predix.eventhub.Publ" +
      "ishResponse\"\000(\0010\0012\221\002\n\nSubscriber\022M\n\007rece" +
      "ive\022$.predix.eventhub.SubscriptionReques" +
      "t\032\030.predix.eventhub.Message\"\0000\001\022X\n\017recei" +
      "veWithAcks\022%.predix.eventhub.Subscriptio" +
      "nResponse\032\030.predix.eventhub.Message\"\000(\0010" +
      "\001\022Z\n\tsubscribe\022!.predix.eventhub.Subscri" +
      "ptionAcks\032$.predix.eventhub.Subscription" +
      "Message\"\000(\0010\001B0\n\033com.ge.predix.eventhub." +
      "stubB\017EventHubServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_predix_eventhub_Timestamp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_predix_eventhub_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_Timestamp_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
    internal_static_predix_eventhub_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_predix_eventhub_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_Message_descriptor,
        new java.lang.String[] { "Id", "Body", "ZoneId", "Tags", "Key", "Topic", "Partition", "Offset", "Timestamp", });
    internal_static_predix_eventhub_Message_TagsEntry_descriptor =
      internal_static_predix_eventhub_Message_descriptor.getNestedTypes().get(0);
    internal_static_predix_eventhub_Message_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_Message_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_predix_eventhub_Ack_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_predix_eventhub_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_Ack_descriptor,
        new java.lang.String[] { "Id", "StatusCode", "Desc", "Topic", "Partition", "Offset", "Timestamp", "Body", "ZoneId", "Tags", "Key", });
    internal_static_predix_eventhub_Ack_TagsEntry_descriptor =
      internal_static_predix_eventhub_Ack_descriptor.getNestedTypes().get(0);
    internal_static_predix_eventhub_Ack_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_Ack_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_predix_eventhub_Messages_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_predix_eventhub_Messages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_Messages_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_predix_eventhub_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_predix_eventhub_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_PublishRequest_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_predix_eventhub_SubscriptionMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_predix_eventhub_SubscriptionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_SubscriptionMessage_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_predix_eventhub_PublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_predix_eventhub_PublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_PublishResponse_descriptor,
        new java.lang.String[] { "Ack", });
    internal_static_predix_eventhub_SubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_predix_eventhub_SubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_SubscriptionResponse_descriptor,
        new java.lang.String[] { "Ack", });
    internal_static_predix_eventhub_SubscriptionAcks_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_predix_eventhub_SubscriptionAcks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_SubscriptionAcks_descriptor,
        new java.lang.String[] { "Ack", });
    internal_static_predix_eventhub_SubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_predix_eventhub_SubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_predix_eventhub_SubscriptionRequest_descriptor,
        new java.lang.String[] { "ZoneId", "Subscriber", "InstanceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
