// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

public interface MessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:predix.eventhub.Messages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .predix.eventhub.Message msg = 1;</code>
   */
  java.util.List<com.ge.predix.eventhub.stub.Message> 
      getMsgList();
  /**
   * <code>repeated .predix.eventhub.Message msg = 1;</code>
   */
  com.ge.predix.eventhub.stub.Message getMsg(int index);
  /**
   * <code>repeated .predix.eventhub.Message msg = 1;</code>
   */
  int getMsgCount();
  /**
   * <code>repeated .predix.eventhub.Message msg = 1;</code>
   */
  java.util.List<? extends com.ge.predix.eventhub.stub.MessageOrBuilder> 
      getMsgOrBuilderList();
  /**
   * <code>repeated .predix.eventhub.Message msg = 1;</code>
   */
  com.ge.predix.eventhub.stub.MessageOrBuilder getMsgOrBuilder(
      int index);
}
