// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

public interface PublishRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:predix.eventhub.PublishRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .predix.eventhub.Messages messages = 1;</code>
   */
  boolean hasMessages();
  /**
   * <code>optional .predix.eventhub.Messages messages = 1;</code>
   */
  com.ge.predix.eventhub.stub.Messages getMessages();
  /**
   * <code>optional .predix.eventhub.Messages messages = 1;</code>
   */
  com.ge.predix.eventhub.stub.MessagesOrBuilder getMessagesOrBuilder();
}
