// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

/**
 * Protobuf type {@code predix.eventhub.PublishRequest}
 */
public  final class PublishRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:predix.eventhub.PublishRequest)
    PublishRequestOrBuilder {
  // Use PublishRequest.newBuilder() to construct.
  private PublishRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublishRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PublishRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.ge.predix.eventhub.stub.Messages.Builder subBuilder = null;
            if (messages_ != null) {
              subBuilder = messages_.toBuilder();
            }
            messages_ = input.readMessage(com.ge.predix.eventhub.stub.Messages.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messages_);
              messages_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_PublishRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_PublishRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ge.predix.eventhub.stub.PublishRequest.class, com.ge.predix.eventhub.stub.PublishRequest.Builder.class);
  }

  public static final int MESSAGES_FIELD_NUMBER = 1;
  private com.ge.predix.eventhub.stub.Messages messages_;
  /**
   * <code>optional .predix.eventhub.Messages messages = 1;</code>
   */
  public boolean hasMessages() {
    return messages_ != null;
  }
  /**
   * <code>optional .predix.eventhub.Messages messages = 1;</code>
   */
  public com.ge.predix.eventhub.stub.Messages getMessages() {
    return messages_ == null ? com.ge.predix.eventhub.stub.Messages.getDefaultInstance() : messages_;
  }
  /**
   * <code>optional .predix.eventhub.Messages messages = 1;</code>
   */
  public com.ge.predix.eventhub.stub.MessagesOrBuilder getMessagesOrBuilder() {
    return getMessages();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messages_ != null) {
      output.writeMessage(1, getMessages());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messages_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessages());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.ge.predix.eventhub.stub.PublishRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ge.predix.eventhub.stub.PublishRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code predix.eventhub.PublishRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:predix.eventhub.PublishRequest)
      com.ge.predix.eventhub.stub.PublishRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_PublishRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_PublishRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ge.predix.eventhub.stub.PublishRequest.class, com.ge.predix.eventhub.stub.PublishRequest.Builder.class);
    }

    // Construct using com.ge.predix.eventhub.stub.PublishRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (messagesBuilder_ == null) {
        messages_ = null;
      } else {
        messages_ = null;
        messagesBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_PublishRequest_descriptor;
    }

    public com.ge.predix.eventhub.stub.PublishRequest getDefaultInstanceForType() {
      return com.ge.predix.eventhub.stub.PublishRequest.getDefaultInstance();
    }

    public com.ge.predix.eventhub.stub.PublishRequest build() {
      com.ge.predix.eventhub.stub.PublishRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ge.predix.eventhub.stub.PublishRequest buildPartial() {
      com.ge.predix.eventhub.stub.PublishRequest result = new com.ge.predix.eventhub.stub.PublishRequest(this);
      if (messagesBuilder_ == null) {
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ge.predix.eventhub.stub.PublishRequest) {
        return mergeFrom((com.ge.predix.eventhub.stub.PublishRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ge.predix.eventhub.stub.PublishRequest other) {
      if (other == com.ge.predix.eventhub.stub.PublishRequest.getDefaultInstance()) return this;
      if (other.hasMessages()) {
        mergeMessages(other.getMessages());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ge.predix.eventhub.stub.PublishRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ge.predix.eventhub.stub.PublishRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.ge.predix.eventhub.stub.Messages messages_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.ge.predix.eventhub.stub.Messages, com.ge.predix.eventhub.stub.Messages.Builder, com.ge.predix.eventhub.stub.MessagesOrBuilder> messagesBuilder_;
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public boolean hasMessages() {
      return messagesBuilder_ != null || messages_ != null;
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public com.ge.predix.eventhub.stub.Messages getMessages() {
      if (messagesBuilder_ == null) {
        return messages_ == null ? com.ge.predix.eventhub.stub.Messages.getDefaultInstance() : messages_;
      } else {
        return messagesBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public Builder setMessages(com.ge.predix.eventhub.stub.Messages value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messages_ = value;
        onChanged();
      } else {
        messagesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public Builder setMessages(
        com.ge.predix.eventhub.stub.Messages.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        messages_ = builderForValue.build();
        onChanged();
      } else {
        messagesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public Builder mergeMessages(com.ge.predix.eventhub.stub.Messages value) {
      if (messagesBuilder_ == null) {
        if (messages_ != null) {
          messages_ =
            com.ge.predix.eventhub.stub.Messages.newBuilder(messages_).mergeFrom(value).buildPartial();
        } else {
          messages_ = value;
        }
        onChanged();
      } else {
        messagesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = null;
        onChanged();
      } else {
        messages_ = null;
        messagesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public com.ge.predix.eventhub.stub.Messages.Builder getMessagesBuilder() {
      
      onChanged();
      return getMessagesFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    public com.ge.predix.eventhub.stub.MessagesOrBuilder getMessagesOrBuilder() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilder();
      } else {
        return messages_ == null ?
            com.ge.predix.eventhub.stub.Messages.getDefaultInstance() : messages_;
      }
    }
    /**
     * <code>optional .predix.eventhub.Messages messages = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.ge.predix.eventhub.stub.Messages, com.ge.predix.eventhub.stub.Messages.Builder, com.ge.predix.eventhub.stub.MessagesOrBuilder> 
        getMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.ge.predix.eventhub.stub.Messages, com.ge.predix.eventhub.stub.Messages.Builder, com.ge.predix.eventhub.stub.MessagesOrBuilder>(
                getMessages(),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:predix.eventhub.PublishRequest)
  }

  // @@protoc_insertion_point(class_scope:predix.eventhub.PublishRequest)
  private static final com.ge.predix.eventhub.stub.PublishRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ge.predix.eventhub.stub.PublishRequest();
  }

  public static com.ge.predix.eventhub.stub.PublishRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishRequest>
      PARSER = new com.google.protobuf.AbstractParser<PublishRequest>() {
    public PublishRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new PublishRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<PublishRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublishRequest> getParserForType() {
    return PARSER;
  }

  public com.ge.predix.eventhub.stub.PublishRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

