// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

public interface SubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:predix.eventhub.SubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string zone_id = 1;</code>
   *
   * <pre>
   * zone name, this will be the user's zone
   * </pre>
   */
  java.lang.String getZoneId();
  /**
   * <code>optional string zone_id = 1;</code>
   *
   * <pre>
   * zone name, this will be the user's zone
   * </pre>
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <code>optional string subscriber = 2;</code>
   *
   * <pre>
   * subscriber name, this will be utilized to parallelize processing
   * </pre>
   */
  java.lang.String getSubscriber();
  /**
   * <code>optional string subscriber = 2;</code>
   *
   * <pre>
   * subscriber name, this will be utilized to parallelize processing
   * </pre>
   */
  com.google.protobuf.ByteString
      getSubscriberBytes();

  /**
   * <code>optional string instance_id = 3;</code>
   *
   * <pre>
   * particular instance of the subscriber
   * </pre>
   */
  java.lang.String getInstanceId();
  /**
   * <code>optional string instance_id = 3;</code>
   *
   * <pre>
   * particular instance of the subscriber
   * </pre>
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();
}
