// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventHub.proto

package com.ge.predix.eventhub.stub;

/**
 * Protobuf type {@code predix.eventhub.SubscriptionAcks}
 */
public  final class SubscriptionAcks extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:predix.eventhub.SubscriptionAcks)
    SubscriptionAcksOrBuilder {
  // Use SubscriptionAcks.newBuilder() to construct.
  private SubscriptionAcks(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SubscriptionAcks() {
    ack_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SubscriptionAcks(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ack_ = new java.util.ArrayList<com.ge.predix.eventhub.stub.Ack>();
              mutable_bitField0_ |= 0x00000001;
            }
            ack_.add(input.readMessage(com.ge.predix.eventhub.stub.Ack.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ack_ = java.util.Collections.unmodifiableList(ack_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_SubscriptionAcks_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_SubscriptionAcks_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ge.predix.eventhub.stub.SubscriptionAcks.class, com.ge.predix.eventhub.stub.SubscriptionAcks.Builder.class);
  }

  public static final int ACK_FIELD_NUMBER = 1;
  private java.util.List<com.ge.predix.eventhub.stub.Ack> ack_;
  /**
   * <code>repeated .predix.eventhub.Ack ack = 1;</code>
   */
  public java.util.List<com.ge.predix.eventhub.stub.Ack> getAckList() {
    return ack_;
  }
  /**
   * <code>repeated .predix.eventhub.Ack ack = 1;</code>
   */
  public java.util.List<? extends com.ge.predix.eventhub.stub.AckOrBuilder> 
      getAckOrBuilderList() {
    return ack_;
  }
  /**
   * <code>repeated .predix.eventhub.Ack ack = 1;</code>
   */
  public int getAckCount() {
    return ack_.size();
  }
  /**
   * <code>repeated .predix.eventhub.Ack ack = 1;</code>
   */
  public com.ge.predix.eventhub.stub.Ack getAck(int index) {
    return ack_.get(index);
  }
  /**
   * <code>repeated .predix.eventhub.Ack ack = 1;</code>
   */
  public com.ge.predix.eventhub.stub.AckOrBuilder getAckOrBuilder(
      int index) {
    return ack_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ack_.size(); i++) {
      output.writeMessage(1, ack_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ack_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ack_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.ge.predix.eventhub.stub.SubscriptionAcks parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ge.predix.eventhub.stub.SubscriptionAcks prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code predix.eventhub.SubscriptionAcks}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:predix.eventhub.SubscriptionAcks)
      com.ge.predix.eventhub.stub.SubscriptionAcksOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_SubscriptionAcks_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_SubscriptionAcks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ge.predix.eventhub.stub.SubscriptionAcks.class, com.ge.predix.eventhub.stub.SubscriptionAcks.Builder.class);
    }

    // Construct using com.ge.predix.eventhub.stub.SubscriptionAcks.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getAckFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (ackBuilder_ == null) {
        ack_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ackBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ge.predix.eventhub.stub.EventHubService.internal_static_predix_eventhub_SubscriptionAcks_descriptor;
    }

    public com.ge.predix.eventhub.stub.SubscriptionAcks getDefaultInstanceForType() {
      return com.ge.predix.eventhub.stub.SubscriptionAcks.getDefaultInstance();
    }

    public com.ge.predix.eventhub.stub.SubscriptionAcks build() {
      com.ge.predix.eventhub.stub.SubscriptionAcks result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ge.predix.eventhub.stub.SubscriptionAcks buildPartial() {
      com.ge.predix.eventhub.stub.SubscriptionAcks result = new com.ge.predix.eventhub.stub.SubscriptionAcks(this);
      int from_bitField0_ = bitField0_;
      if (ackBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ack_ = java.util.Collections.unmodifiableList(ack_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ack_ = ack_;
      } else {
        result.ack_ = ackBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ge.predix.eventhub.stub.SubscriptionAcks) {
        return mergeFrom((com.ge.predix.eventhub.stub.SubscriptionAcks)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ge.predix.eventhub.stub.SubscriptionAcks other) {
      if (other == com.ge.predix.eventhub.stub.SubscriptionAcks.getDefaultInstance()) return this;
      if (ackBuilder_ == null) {
        if (!other.ack_.isEmpty()) {
          if (ack_.isEmpty()) {
            ack_ = other.ack_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAckIsMutable();
            ack_.addAll(other.ack_);
          }
          onChanged();
        }
      } else {
        if (!other.ack_.isEmpty()) {
          if (ackBuilder_.isEmpty()) {
            ackBuilder_.dispose();
            ackBuilder_ = null;
            ack_ = other.ack_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ackBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAckFieldBuilder() : null;
          } else {
            ackBuilder_.addAllMessages(other.ack_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ge.predix.eventhub.stub.SubscriptionAcks parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ge.predix.eventhub.stub.SubscriptionAcks) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ge.predix.eventhub.stub.Ack> ack_ =
      java.util.Collections.emptyList();
    private void ensureAckIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ack_ = new java.util.ArrayList<com.ge.predix.eventhub.stub.Ack>(ack_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.ge.predix.eventhub.stub.Ack, com.ge.predix.eventhub.stub.Ack.Builder, com.ge.predix.eventhub.stub.AckOrBuilder> ackBuilder_;

    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public java.util.List<com.ge.predix.eventhub.stub.Ack> getAckList() {
      if (ackBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ack_);
      } else {
        return ackBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public int getAckCount() {
      if (ackBuilder_ == null) {
        return ack_.size();
      } else {
        return ackBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public com.ge.predix.eventhub.stub.Ack getAck(int index) {
      if (ackBuilder_ == null) {
        return ack_.get(index);
      } else {
        return ackBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder setAck(
        int index, com.ge.predix.eventhub.stub.Ack value) {
      if (ackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAckIsMutable();
        ack_.set(index, value);
        onChanged();
      } else {
        ackBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder setAck(
        int index, com.ge.predix.eventhub.stub.Ack.Builder builderForValue) {
      if (ackBuilder_ == null) {
        ensureAckIsMutable();
        ack_.set(index, builderForValue.build());
        onChanged();
      } else {
        ackBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder addAck(com.ge.predix.eventhub.stub.Ack value) {
      if (ackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAckIsMutable();
        ack_.add(value);
        onChanged();
      } else {
        ackBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder addAck(
        int index, com.ge.predix.eventhub.stub.Ack value) {
      if (ackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAckIsMutable();
        ack_.add(index, value);
        onChanged();
      } else {
        ackBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder addAck(
        com.ge.predix.eventhub.stub.Ack.Builder builderForValue) {
      if (ackBuilder_ == null) {
        ensureAckIsMutable();
        ack_.add(builderForValue.build());
        onChanged();
      } else {
        ackBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder addAck(
        int index, com.ge.predix.eventhub.stub.Ack.Builder builderForValue) {
      if (ackBuilder_ == null) {
        ensureAckIsMutable();
        ack_.add(index, builderForValue.build());
        onChanged();
      } else {
        ackBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder addAllAck(
        java.lang.Iterable<? extends com.ge.predix.eventhub.stub.Ack> values) {
      if (ackBuilder_ == null) {
        ensureAckIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ack_);
        onChanged();
      } else {
        ackBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder clearAck() {
      if (ackBuilder_ == null) {
        ack_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ackBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public Builder removeAck(int index) {
      if (ackBuilder_ == null) {
        ensureAckIsMutable();
        ack_.remove(index);
        onChanged();
      } else {
        ackBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public com.ge.predix.eventhub.stub.Ack.Builder getAckBuilder(
        int index) {
      return getAckFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public com.ge.predix.eventhub.stub.AckOrBuilder getAckOrBuilder(
        int index) {
      if (ackBuilder_ == null) {
        return ack_.get(index);  } else {
        return ackBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public java.util.List<? extends com.ge.predix.eventhub.stub.AckOrBuilder> 
         getAckOrBuilderList() {
      if (ackBuilder_ != null) {
        return ackBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ack_);
      }
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public com.ge.predix.eventhub.stub.Ack.Builder addAckBuilder() {
      return getAckFieldBuilder().addBuilder(
          com.ge.predix.eventhub.stub.Ack.getDefaultInstance());
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public com.ge.predix.eventhub.stub.Ack.Builder addAckBuilder(
        int index) {
      return getAckFieldBuilder().addBuilder(
          index, com.ge.predix.eventhub.stub.Ack.getDefaultInstance());
    }
    /**
     * <code>repeated .predix.eventhub.Ack ack = 1;</code>
     */
    public java.util.List<com.ge.predix.eventhub.stub.Ack.Builder> 
         getAckBuilderList() {
      return getAckFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.ge.predix.eventhub.stub.Ack, com.ge.predix.eventhub.stub.Ack.Builder, com.ge.predix.eventhub.stub.AckOrBuilder> 
        getAckFieldBuilder() {
      if (ackBuilder_ == null) {
        ackBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.ge.predix.eventhub.stub.Ack, com.ge.predix.eventhub.stub.Ack.Builder, com.ge.predix.eventhub.stub.AckOrBuilder>(
                ack_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        ack_ = null;
      }
      return ackBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:predix.eventhub.SubscriptionAcks)
  }

  // @@protoc_insertion_point(class_scope:predix.eventhub.SubscriptionAcks)
  private static final com.ge.predix.eventhub.stub.SubscriptionAcks DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ge.predix.eventhub.stub.SubscriptionAcks();
  }

  public static com.ge.predix.eventhub.stub.SubscriptionAcks getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscriptionAcks>
      PARSER = new com.google.protobuf.AbstractParser<SubscriptionAcks>() {
    public SubscriptionAcks parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new SubscriptionAcks(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<SubscriptionAcks> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscriptionAcks> getParserForType() {
    return PARSER;
  }

  public com.ge.predix.eventhub.stub.SubscriptionAcks getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

